Fish 7957 fix webservices jacc tck
payara/jakartaeetck-runner pull request #91
Opened 2023-11-06 14:05 UTC by aubi

Fixes webservices and jacc TCKs
Includes James' change of handling derby files

2023-11-08 09:10 UTC, Pandrex247 requested changes

2023-11-08 09:10 UTC, Pandrex247 commented on run.sh
> -    cp patch/ant_sun.jar $CTS_HOME/jakartaeetck/lib/ant_sun.jar
Why are you removing this? This is important
Without this we fail the TCK if the Payara version contains "8"

2023-11-08 09:20 UTC, Pandrex247 commented on run.sh
> -    cp patch/ant_sun.jar $CTS_HOME/jakartaeetck/lib/ant_sun.jar
See:
* https://github.com/payara/jakartaeetck-runner/pull/85
* https://github.com/payara/patched-src-jakartaee-tck-tools/pull/1/files

2023-11-09 16:45 UTC, aubi commented
Fixed, running new build now.

2023-11-09 16:50 UTC, breakponchito approved these changes
LGTM

2023-11-10 09:12 UTC, Pandrex247 approved these changes

2023-11-10 09:18 UTC, merged